### ISSUE TITLE
Could not find a type named SubcoreInfo.Comps.CompEjected

### ISSUE THREAD

**Issue by LionelColaso** [eth0net/SubcoreInfo#1]
[Player.log](https://github.com/eth0net/SubcoreInfo/files/11104841/Player.log)

Could not find a type named SubcoreInfo.Comps.CompEjected
SubcoreRipscanner (mod Biotech) is missing comp class from one of comps and will not work properly.
SubcoreSoftscanner (mod Biotech) is missing comp class from one of comps and will not work properly.

**Comment by eth0net** [comment]
Oh man sorry about that! I was working on some optimisations and must have missed that somehow!

**Comment by eth0net** [comment]
Curious, I've run through some tests and it all worked fine. I did remove that type as it's no longer needed, but I've checked and there is no attempt to load it now. Perhaps the rocketman cache was holding the ref to it still - could you please try clearing your rocketman cache? :)

**Comment by LionelColaso** [comment]
seems like mod was not updating properly even when it showed updated
manually deleting mod folder and downloading using rimpy fixed it
Sorry for the inconvenience

**Comment by eth0net** [comment]
No worries, glad it's sorted 🥳 Enjoy!
